name = "mosaic-pm"
main = "build/worker/shim.mjs"
compatibility_date = "2025-02-03"

[[d1_databases]]
binding = "MPM_DB"
database_name = "mosaicpm"

[build]
command = "cargo install -q worker-build && worker-build --release"